/**
 * Generates src/data/players.ts from the inline catalog plus expansion fills.
 * Run: node scripts/generate-players.mjs
 *
 * Duplicate name+franchise+decade rows keep the highest-tier copy so later
 * catalogs can patch holes without minting -2 ids.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { EXPANSION } from './player-expansion.mjs';
import { ROSTER_FILL } from './roster-fill.mjs';
import { ROSTER_NINE } from './roster-nine.mjs';
import { HOF_NAMES } from './hof-names.mjs';
import { RAW_1 } from './raw-1.mjs';
import { RAW_2 } from './raw-2.mjs';
import { RAW_3 } from './raw-3.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** [name, franchise, decade, positions, tier, hof, avg|era, obp|whip, slg|k9, isPitcher] */
const RAW = [...RAW_1, ...RAW_2, ...RAW_3, ...EXPANSION, ...ROSTER_FILL, ...ROSTER_NINE];

const OF = new Set(['LF', 'CF', 'RF']);
const VALID = new Set(['C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF', 'SP']);

function expandPositions(raw) {
  const parts = raw.split(',').map((p) => p.trim()).filter(Boolean);
  const out = new Set();
  for (const p of parts) {
    if (p === 'OF') {
      OF.forEach((x) => out.add(x));
    } else if (p === 'DH') {
      // DH can fill corner OF or 1B in this game
      out.add('1B');
      out.add('LF');
      out.add('RF');
    } else if (VALID.has(p)) {
      out.add(p);
    }
  }
  // Generic OF eligibility
  if ([...out].some((p) => OF.has(p))) {
    // keep as listed only
  }
  return [...out];
}

const seen = new Set();
const bestByPersonEra = new Map();
const nameCounts = new Map();

for (const row of RAW) {
  const name = row[0];
  nameCounts.set(name, (nameCounts.get(name) ?? 0) + 1);
}

for (const row of RAW) {
  const [name, franchiseId, decade, posRaw, tier, hof, a, b, c, isPitcher] = row;
  const positions = expandPositions(posRaw);
  if (positions.length === 0) continue;
  const personEra = `${name}|${franchiseId}|${decade}`;
  const prev = bestByPersonEra.get(personEra);
  if (prev && prev.tier >= tier) continue;
  bestByPersonEra.set(personEra, { name, franchiseId, decade, positions, tier, hof, a, b, c, isPitcher });
}

const players = [];
for (const row of bestByPersonEra.values()) {
  const { name, franchiseId, decade, positions, tier, hof, a, b, c, isPitcher } = row;
  const baseId = `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${franchiseId}-${decade}`;
  let id = baseId;
  let n = 2;
  while (seen.has(id)) {
    id = `${baseId}-${n++}`;
  }
  seen.add(id);

  const player = {
    id,
    name,
    franchiseId,
    decade,
    positions,
    tier,
    hof: Boolean(hof) || ((nameCounts.get(name) ?? 0) === 1 && HOF_NAMES.has(name)),
  };

  if (isPitcher) {
    player.pitching = { era: a, whip: b, k9: c };
  } else {
    player.batting = { avg: a, obp: b, slg: c };
  }
  players.push(player);
}

const out = `/* Auto-generated by scripts/generate-players.mjs — do not edit by hand */
import type { Player } from '../types/game';

// Parsed at runtime so tsc does not have to type-check 2,000 object literals.
export const PLAYERS: Player[] = JSON.parse(${JSON.stringify(JSON.stringify(players))});

export function playersForSpin(franchiseId: string, decade: string): Player[] {
  return PLAYERS.filter((p) => p.franchiseId === franchiseId && p.decade === decade);
}
`;

writeFileSync(join(__dirname, '../src/data/players.ts'), out);

// A tiny companion module so spin logic can answer "which franchise-decades
// exist?" without pulling the whole player table into the initial bundle.
const populatedKeys = [...new Set(players.map((p) => `${p.franchiseId}|${p.decade}`))].sort();
const indexOut = `/* Auto-generated by scripts/generate-players.mjs — do not edit by hand */

/** Every franchise-decade that has at least one player. */
export const POPULATED_KEYS: readonly string[] = ${JSON.stringify(populatedKeys, null, 2)};
`;
writeFileSync(join(__dirname, '../src/data/poolIndex.ts'), indexOut);

console.log(`Wrote ${players.length} players across ${populatedKeys.length} franchise-decades`);
